import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserProvider from "@/context/userContext";
import { SocketProvider } from "@/context/useSocket";
import { ThemeProvider } from "@/component/theme-provider";
import ThemeToggle from "@/component/(HomePage)/ToggleTheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider>
          <UserProvider>
            <ThemeToggle />
            <SocketProvider>{children}</SocketProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
